source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'EventBlankKit', path: '.'

target 'EventBlank2-iOS' do
	platform :ios, '10.0'
	
	# rx
    pod 'RxSwift', '4.0.0'
    pod 'RxCocoa', '4.0.0'
    pod 'RxFeedback', '1.0.0'
    pod 'RxDataSources', '3.0.1'
    pod 'RxGesture', '1.2.1'
    pod 'RxRealm', '0.7.4'
    pod 'RxViewController', '0.3.0'

	# realm
    pod 'RealmSwift', '3.0.1'
    pod 'RealmContent', '0.2.5'

	# visual
    pod 'MAThemeKit', '1.0'
    pod 'DynamicColor', '3.3'
    pod 'NSString+Color', '1.1.4'

	# views
    pod 'XLPagerTabStrip', '7.0.0'
    pod 'SwiftMessages', '3.4.0'
    pod 'SwiftSpinner', '1.4.1'
    pod 'KRWalkThrough', '0.10.2'

	# network
    pod 'SwiftyJSON', '3.1.4'
    pod 'Reachability', '3.2'
    pod 'Kingfisher', '4.2.0'

	# etc
    pod 'AcknowList', '1.4.0'
    pod 'Then', '2.2.1'
    pod 'AFDateHelper', '4.2.6'
    pod 'RelativeFormatter', '0.8.3'
end

#
# Test target for EventBlankKit
#
target 'EventBlankKit-Tests' do
	platform :ios, '10.0'

    pod 'RxSwift', '4.0.0'
    pod 'RxCocoa', '4.0.0'
    pod 'RxTest', '4.0.0'
    pod 'RxBlocking', '4.0.0'
end

#
# Connection Keys
#

plugin 'cocoapods-keys', {
    :project => "EventBlank2-iOS",
    :keys => [ "scheme", "host", "port", "username", "password", "path" ]
}

#
# Temporary set swift version from Podfile
#
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Signing
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''

            # Swift4 pods
            next unless target.name.start_with?("Rx") ||
                target.name.start_with?("Realm") ||
                target.name.start_with?("Kingfisher") ||
                target.name.start_with?("AFDateHelper") ||
                target.name.start_with?("EventBlankKit") ||
                target.name.start_with?("AcknowList") 

            config.build_settings['SWIFT_VERSION'] = '4.0'

        end
    end
end

